* Thunderhorse - An Org-Mode parser for Common Lisp

#+begin_quote
[[https://piped.kavin.rocks/watch?v=QuphOxBX8YI][Thunder... Thunder... Horse... Horse...]]
#+end_quote


This is a work-in-progress Org-Mode parser for Common Lisp. The goal is to
eventually be compliant with the core markup functionality specified by [[https://karl-voit.at/2021/11/27/orgdown/][Orgdown]],
and then also whatever additional features I personally use Org-Mode for
(especially the metadata features like tags). This makes extensive use of CLOS
to return the AST of an Org-Mode document as a standard object so that you can
do whatever you want with it.

I don't recommend even trying to use this right now or looking at the code for
that matter.

** Why?

There are two Org-Mode parsers for CL currently. Both are incomplete and for
different reasons it seemed more productive to just implement one myself instead
of trying to figure out how to finish the other two. This doesn't use any fancy
parsing techniques, but I don't personally care if it's the fastest thing ever
as long as it works since GNU Emacs doesn't set a very high bar to begin with.

** Compliance

- [-] Orgdown-1
  - [X] Basic headings
  - [ ] Greater Elements
    - [ ] Tables
    - [ ] Lists
    - [ ] Basic blocks
  - [-] Lesser Elements
    - [-] Paragraphs
    - [ ] Inline text markup (bold, italics, etc)
    - [ ] Links
    - [ ] Comments
- [-] Orgdown-?2
  - [X] Heading metadata
    - [X] Todo states
    - [X] Priorities
    - [X] Tags
  - [-] Greater Elements
    - [-] Drawers
    - [ ] Block metadata

** Naming

Idk Org-Mode's mascot is a unicorn and the only sort of related thing I could
think of is the Dethklok song. I make no promises of this being Lightning Fast™.

** License

ISC. Do whatever you want with it, just make sure to credit me.
